### ISSUE TITLE
Replace parcel watcher

### ISSUE THREAD

**Issue by hpx7** [vinsonchuong/hot-esm#20]
Would you be open to using https://www.npmjs.com/package/chokidar instead? It avoids the C++ bindings with node-gyp and is more popular in general

**Comment by vinsonchuong** [comment]
Hi again! I'm open to switching to Chokidar.

All of the file watchers libraries tend to have similar APIs.

I guess the only differentiating factor is performance. But, from a quick search, it doesn't seem like folks are interested enough to do benchmarks. So I guess my stance is I don't care until I'm running this on a project big enough to slow it down.

Reducing number of annoying dependencies is worthwhile in my book.

I'll do it this weekend, unless you're already in it and make a PR first :P

Cheers

**Comment by hpx7** [comment]
Awesome! It looks like chokidar switched from node-gyp to N-API, and generally trimmed down their deps. Ultimately it lead for a much faster installation time (right now `hot-esm` is quite slow to install because of `@parcel/watcher`) and smaller `node_modules` footprint.

If you're curious, there are some more details here: https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/

**Comment by vinsonchuong** [comment]
@hpx7, I pushed a change to switch over to chokidar. It's released as `v1.1.0`.

Let me know if it is working for you!

**Comment by hpx7** [comment]
@vinsonchuong looks to be working great, thanks!
