### ISSUE TITLE
[NEW FEATURE] Possibility override default exclusion node_modules for hot ESM reloading.

### ISSUE THREAD

**Issue by dtoch** [vinsonchuong/hot-esm#22]
As documented in https://www.npmjs.com/package/hot-esm 

"Also, edits to files in node_modules, even if they are ECMAScript Modules are ignored as attaching filesystem watchers to so many directories is too expensive."

However sometimes it would be useful to override this behaviour for example if you would need to have hot esm reloading of ESM modules of a specific package in node_modules/ that was developed by ourself.

**Comment by vinsonchuong** [comment]
Hi @dtoch, I've done some initial work for this feature.

Released in `v1.2.0`, you can set a the `HOT_INCLUDE_PACKAGES=package1,package2` environment variable. It is comma-separated with no spaces.

I still need to do more testing to make sure symlinks and hard links work correctly. But, when you get the chance, let me know if it works for you.
