### ISSUE TITLE
Switch to new loader hooks api

### ISSUE THREAD

**Issue by hpx7** [vinsonchuong/hot-esm#23]
See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.12.0

**Comment by vinsonchuong** [comment]
Reading through the [pull request](https://github.com/nodejs/node/pull/37468/files#diff-f404db6c314f6baf7acc00e537fd4ade2761d9674199268712e6102ee3136c6b) that changes the interface, it looks like the changes include:

- `resolve` now returns an object containing `url` and optionally `format`.
- If a `format` is returned by `resolve`, I have to define a custom `load` hook.

So, if `defaultResolve` returns a `format` key, I have to do the above two things. The documentation doesn't make it clear whether `defaultResolve` will ever return a `format` though.

I did try to come up with a failing test case by importing a JSON file and trying to require a CommonJS file, but I wasn't able to get `defaultResolve` to return a format.

I'm going to go ahead and make sure my `resolve` returns `format` if `defaultResolve` does. And, also, I'll define a `load` hook that just calls `defaultLoad`.

My existing test cases pass in Node.js `v16.11.1`, `v16.12.0`, and `v17.0.1` before and after the change.

**Comment by vinsonchuong** [comment]
@hpx7, let me know if you're actually seeing breakages with Node `v16.12.0` or `v17.0.1`. Or, if you're able to see a change in the docs that I missed.

I just released `v1.2.2` of the package with the change indicated in my previous comment.

**Comment by hpx7** [comment]
Forgot to update you, but the latest version is working great!
