### ISSUE TITLE
Configurable watch directory

### ISSUE THREAD

**Issue by hpx7** [vinsonchuong/hot-esm#24]
For my use case (a monorepo), files can imported from outside the current working directory. Because of [this line](https://github.com/vinsonchuong/hot-esm/blob/456dc02e6bfcc5e403f93c3a77ce10e3125fc305/index.js#L68), hot-esm currently only watches for file changes inside the cwd, causing files outside to not be reloaded.

One way to solve this would be to use an environment variable `HOT_ROOT_DIR` as a way to the configure watch directory.

What do you think?

**Comment by vinsonchuong** [comment]
Allowing the root directory to be configured sounds good to me. I'll try to get a new version with the change pushed out tonight.

I was thinking about whether the library can be clever about adding listeners as files are imported. I'd have to read through how Chokidar works under the hood to figure out the performance implications of doing it like this.

**Comment by hpx7** [comment]
I really like the idea of only watching files that are imported. This avoids any manual configuration, and I think in many cases can be more efficient because no extraneous files will need to be watched.

I can send a patch for this functionality if you'd like.
